import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import React from 'react'
import styles from '../styles/Home.module.css'
// import acai from '../assets/acai.png'; // with import
export default function Home() {
  const [posts, setPosts] = useState([]);

  useEffect(async () => {
    const resposta = await fetch("https://jsonplaceholder.typicode.com/posts");
    const final = await resposta.json();
    await setPosts(final);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.posts}>
      {posts?.map((res)=>{
        return (
          <div key={res.id} className={styles.textStyle}>
          <h4 className={styles.title}>{res.title}</h4>
          <div className={styles.image}>
          <Image
            // src="http://placekitten.com/200/300"
            src="/assets/1.png"
            alt="Picture of the author"
            width={550}
            height={550}
          />
          </div>
          <small className={styles.description}>{res.body}</small>
          <small className={styles.show}><a href="">Ver mais...</a></small>
          <br />
          <div className={styles.comprar}>
          <button>Comprar</button>
          <div>R$ 580,00</div>
          </div>
          </div>
        )
      })}
      <footer className={styles.footer}>
        Vaca pé
      </footer>
      </main>
    </div>
  )
}
